In [9]:
# Upgrade dependencies
!pip install -r ../requirements.txt

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
  Using cached nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 35.8 MB/s eta 0:00:0000:010:01
  Using cached nltk-3.6.2-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 120.2 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 31.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 50.6 MB/s eta 0:00:0000:0100:01
  Using cached trax-1.3.7-py2.py3-none-any.whl (521 kB)
  Using cached transformers-4.5.1-py3-none-any.whl (2.1 MB)
  Using cached datasets-2.1.0-py3-none-any.whl (325 kB)
  Using cached gsutil-5.5.tar.gz (2.9 MB)
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.3/71.3 MB 30.8 MB/s eta 0:00:0000:0100:01
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
  Using c

  Using cached boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
  Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
  Using cached pyu2f-0.1.5.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.25.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.24.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.23.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.22.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.21.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.20.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.19.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.17.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.16.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.3.15.tar.gz (1.0 MB)
  Prepar

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 37.1 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 kB 90.2 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of pyparsing to determine which version is compatible with other requirements. This could take a while.
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
INFO: pip is looking at multiple versions of protobuf to determine which version is compatible with other requirements. This could take a while.
  Using cached protobuf-4.21.12-cp37-abi3-manylinux2014_x86_64.whl (409 kB)
INFO: pip is looking at multiple versions of oauth2client to determine which version is compatible with other requirements. This could take a while.
  Using cached oauth2client-4.1.2-py2.py3-none-any.whl (99 kB)
INFO: pip is looking at multiple versions of multidict to de

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 MB 1.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.7/511.7 MB 1.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.7/511.7 MB 1.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 41.7 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.1/498.1 MB 1.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 70.7 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.3/462.3 kB 69.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.5/498.5 MB 1.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.0/498.0 MB 1.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.0/498.0 MB 1.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 497.6/497.6 MB 1.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━

In [10]:
# !pip install datasets==2.1.0
import boto3
import os
from os import path
import pandas as pd
import time
import torch
import re
import string
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk.tokenize import word_tokenize

In [11]:
# !pip install --upgrade numpy

## 1. Reading the dataset

We will use the __pandas__ library to read our dataset. Let's first download the files.

#### __Training data:__

In [12]:
train_df = pd.read_csv('../data/train_complete.csv', encoding='utf-8', header=0)
train_df.head()

tweet  label
0  "QT @user In the original draft of the 7th boo...      2
1  "Ben Smith / Smith (concussion) remains out of...      1
2  Sorry bout the stream last night I crashed out...      1
3  Chase Headley's RBI double in the 8th inning o...      1
4  @user Alciato: Bee will invest 150 million in ...      2

#### __Test data:__

In [13]:
lines = []
with open('../data/test_text.txt') as f:
    lines = [line.rstrip('\n') for line in f]
print(len(lines))
test_df = pd.DataFrame (lines, columns = ['tweet'])
test_df.head()

12284


tweet
0  @user @user what do these '1/2 naked pics' hav...
1  OH: “I had a blue penis while I was this” [pla...
2  @user @user That's coming, but I think the vic...
3  I think I may be finally in with the in crowd ...
4  @user Wow,first Hugo Chavez and now Fidel Cast...

In [14]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47615 entries, 0 to 47614
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   tweet   47615 non-null  object
 1   label   47615 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 744.1+ KB


In [15]:
# Checking if there is imbalance
class_id_distribution = train_df['label'].value_counts()
print(class_id_distribution)

1    21542
2    18668
0     7405
Name: label, dtype: int64


In [16]:
train_df.dropna(subset=["tweet"], inplace=True)

In [17]:
!pip install numpy
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score
from transformers import Trainer, TrainingArguments, DistilBertForSequenceClassification, DistilBertTokenizerFast
from torch.utils.data import DataLoader
from datasets import load_metric

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com


ModuleNotFoundError: No module named 'transformers'

In [ ]:
# This separates 10% of the entire train dataset into validation dataset.
train_texts, val_texts, train_labels, val_labels = train_test_split(
    train_df[["tweet"]],
    train_df["label"].values,
#     train_df["tweet"].tolist(),
#     train_df["label"].values.tolist(),
    test_size=0.10,
    shuffle=True,
    random_state=324,
    stratify = train_df["label"].tolist(),
)

In [ ]:
print(train_texts)

In [60]:
# Making the samples equal for each class
X_train_sample_class_0 = train_texts[train_labels == 0]
X_train_sample_class_1 = train_texts[train_labels == 1]
X_train_sample_class_2 = train_texts[train_labels == 2]

from sklearn.utils import resample
X_train_sample_class_1 = resample(X_train_sample_class_1,
             replace=True,
             n_samples=X_train_sample_class_0.shape[0]+3000,
             random_state=42)
X_train_sample_class_2 = resample(X_train_sample_class_2,
             replace=True,
             n_samples=X_train_sample_class_0.shape[0]+3000,
             random_state=42)
y_train_sample_class_0 = np.zeros(X_train_sample_class_0.shape[0])
y_train_sample_class_1 = np.ones(X_train_sample_class_1.shape[0])
y_train_sample_class_2 = np.repeat(2, X_train_sample_class_2.shape[0])
print(X_train_sample_class_1.shape)
print(X_train_sample_class_2.shape)

train_texts = pd.concat([pd.concat([X_train_sample_class_0, X_train_sample_class_1]), X_train_sample_class_2])
train_labels = np.concatenate((np.concatenate((y_train_sample_class_0, y_train_sample_class_1), axis=0), y_train_sample_class_2), axis=0)
print(train_texts.shape)
print(train_labels.shape)

(9664, 1)
(9664, 1)
(25992, 1)
(25992,)


In [ ]:

# def process_text(texts):
#     final_text_list = []
#     for sent in texts:

#         # Check if the sentence is a missing value
#         if isinstance(sent, str) == False:
#             sent = ""

#         filtered_sentence = []
        
#         # Lowercase
#         sent = sent.lower()
#         # Remove leading/trailing whitespace
#         sent = sent.strip()
#         # Remove extra space and tabs
#         sent = re.sub("\s+", " ", sent)
#         # Remove HTML tags/markups:
#         sent = re.compile("<.*?>").sub("", sent)
        
#         punc = '''!"'#$%&()*+,-./:;<=>?@[\]^_`{|}~'''

#         # Removing punctuations in string
#         # Using loop + punctuation string
#         for ele in sent:
#             if ele in punc:
#                 sent = sent.replace(ele, "")
        
# #         sent = ''.join([i for i in sent if not i.isdigit()])

# #         words = word_tokenize(sent)
    
# #         #NOTHING
# #         for w in words:
# #             if (not w.isnumeric()) and len(w)>3:
# #                 filtered_sentence.append(w)
        
# #         #STEMMING
# #         for w in words:
# #             # Check if it is not numeric and its length>2 and not in stop words
# #             if (not w.isnumeric()) and (len(w) > 2):
# #                 # Stem and add to filtered list
# #                 filtered_sentence.append(snow.stem(w))

# #         #LEMMITIZATION
# #         wl = WordNetLemmatizer()
# #         for w in words:
# #             if (not w.isnumeric()) and (w not in stop_words):
# #                 filtered_sentence.append(w)
# #         sent = " ".join(filtered_sentence)
# #         filtered_sentence = []
        
# #         words = word_tokenize(sent)
# #         # Get position tags
# #         word_pos_tags = nltk.pos_tag(words)
# #         # Map the position tag and lemmatize the word/token
# #         for idx, tag in enumerate(word_pos_tags):
# #             filtered_sentence.append(wl.lemmatize(tag[0], get_wordnet_pos(tag[1])))
    
# #         final_string = " ".join(sent)  # final string of cleaned words

#         final_text_list.append(sent)

#     return final_text_list

# print("Processing the text fields...")
# train_texts["tweet"] = process_text(train_texts["tweet"].tolist())
# val_texts["tweet"] = process_text(val_texts["tweet"].tolist())
# print(train_texts.shape)
# print(val_texts.shape)

In [ ]:
# Stop words removal and stemming
# Let's get a list of stop words from the NLTK library
stop = stopwords.words("english")
stop_words = [word for word in stop]

snow = SnowballStemmer("english")

def process_text(texts):
    final_text_list = []
    for sent in texts:

        filtered_sentence = []
        
        # convert to lowercase
        sent = sent.lower()
        # Remove leading/trailing whitespace
        sent = sent.strip()
        # Remove extra space and tabs
        sent = re.sub("\s+", " ", sent)
        # Remove retweets, links, hashtags
        sent = re.sub('@[^\s]+','',sent) 
        sent = re.sub('http[^\s]+','',sent)
        sent = re.sub('#[^\s]+','',sent)
        # Remove numerics
        sent = ''.join([i for i in sent if not i.isdigit()])
        # Remove emojis
        emojis = re.compile("["
            u"\U0001F600-\U0001F64F"  # emoticons
            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
            u"\U0001F680-\U0001F6FF"  # transport & map symbols
            u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
            u"\U00002500-\U00002BEF"  # chinese char
            u"\U00002702-\U000027B0"
            u"\U00002702-\U000027B0"
            u"\U000024C2-\U0001F251"
            u"\U0001f926-\U0001f937"
            u"\U00010000-\U0010ffff"
            u"\u2640-\u2642" 
            u"\u2600-\u2B55"
            u"\u200d"
            u"\u23cf"
            u"\u23e9"
            u"\u231a"
            u"\ufe0f"  # dingbats
            u"\u3030""]+", re.UNICODE)
        sent = re.sub(emojis, '', sent)
        # Remove some unicode characters
        sent = sent.replace('\u2019', '')
        sent = sent.replace('\u002c', '')
        
        # Tokenize the sentence
        words = word_tokenize(sent)
        
        for i in range(len(words)):
            filtered_sentence.append((words[i]))
            
#         #STEMMING
#         for i in range(len(words)):
#             # Check if its length>2
#             if len(words[i])>2:
#                 # Stem and add to filtered list
#                 filtered_sentence.append(snow.stem(words[i]))
    
        final_string = " ".join(filtered_sentence)  # final string of cleaned words

        final_text_list.append(final_string)

    return final_text_list

print("Processing the text fields...")

train_texts["tweet"] = process_text(train_texts["tweet"].tolist())
val_texts["tweet"] = process_text(val_texts["tweet"].tolist())
test_df["tweet"] = process_text(test_df["tweet"].tolist())
print(train_texts.shape)
print(val_texts.shape)

# Remove punctuations
punctuations_list = string.punctuation
def cleaning_punctuations(text):
    translator = str.maketrans('', '', punctuations_list)
    return text.translate(translator)

train_texts["tweet"] = train_texts["tweet"].apply(lambda x: cleaning_punctuations(x))
val_texts["tweet"] = val_texts["tweet"].apply(lambda x: cleaning_punctuations(x))
test_df["tweet"] = test_df["tweet"].apply(lambda x: cleaning_punctuations(x))

In [ ]:
print(train_texts)

In [ ]:
train_texts = train_texts['tweet'].astype(str).tolist()
val_texts = val_texts['tweet'].astype(str).tolist()

In [ ]:
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

train_encodings = tokenizer(train_texts,
                            truncation=True,
                            padding=True)
val_encodings = tokenizer(val_texts,
                          truncation=True,
                          padding=True)

In [ ]:
# Data preparation
class ReviewDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]).to(device) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)
        return item

    def __len__(self):
        return len(self.labels)
    
train_dataset = ReviewDataset(train_encodings, train_labels)
val_dataset = ReviewDataset(val_encodings, val_labels)

In [ ]:
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased",
                                                            num_labels=3)

## 2. Train a Classifier

In [73]:
# Implement this
# Freeze the encoder weights until the classfier
for name, param in model.named_parameters():
    if "classifier" not in name:
        param.requires_grad = False

# Hyperparameters
num_epochs = 10
learning_rate=0.001

# Get the compute device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create data loaders
train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=8, drop_last=True)
eval_dataloader = DataLoader(val_dataset, batch_size=8, drop_last=True)

# Setup the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

metric = load_metric("f1")

model=model.to(device)

for epoch in range(num_epochs):
    start = time.time()
    training_loss = 0
    val_loss = 0
    # Training loop starts
    model.train() # put the model in training mode
    for batch in train_dataloader:
        # below: ** allows us to pass multiple arguments to model()
        outputs = model(**batch)
        loss = outputs.loss
        training_loss += loss.item()
        loss.backward()

        optimizer.step()
        optimizer.zero_grad()
    
    # Validation loop starts
    model.eval() # put the model in prediction mode
    for batch in eval_dataloader:
        with torch.no_grad():
            # below:  ** allows us to pass multiple arguments to model()
            outputs = model(**batch)
        loss = outputs.loss
        val_loss += loss.item()
        logits = outputs.logits
        predictions = torch.argmax(logits, dim=-1)
        metric.add_batch(predictions=predictions, references=batch["labels"])
        
    # Let's take the average losses
    training_loss = training_loss / len(train_dataloader)
    val_loss = val_loss / len(eval_dataloader)
    end = time.time()
    
    print(f"Epoch {epoch}. Train_loss {training_loss:.4f}. Val_loss {val_loss:.4f}. \
    Val_accuracy {metric.compute(average='macro')['f1']:.4f}. Seconds {end-start:.3f}.")

/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 0. Train_loss 0.8465. Val_loss 0.8220.     Val_accuracy 0.5805. Seconds 46.471.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 1. Train_loss 0.8392. Val_loss 0.8412.     Val_accuracy 0.5744. Seconds 47.141.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 2. Train_loss 0.8367. Val_loss 0.8227.     Val_accuracy 0.5884. Seconds 47.088.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 3. Train_loss 0.8291. Val_loss 0.8340.     Val_accuracy 0.5865. Seconds 47.089.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 4. Train_loss 0.8258. Val_loss 0.8242.     Val_accuracy 0.5951. Seconds 47.470.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 5. Train_loss 0.8195. Val_loss 0.8109.     Val_accuracy 0.5964. Seconds 47.190.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 6. Train_loss 0.8157. Val_loss 0.7982.     Val_accuracy 0.6015. Seconds 48.409.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 7. Train_loss 0.8132. Val_loss 0.8375.     Val_accuracy 0.5770. Seconds 50.756.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 8. Train_loss 0.8121. Val_loss 0.8163.     Val_accuracy 0.5907. Seconds 54.012.


/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


Epoch 9. Train_loss 0.8107. Val_loss 0.8063.     Val_accuracy 0.6004. Seconds 54.113.


# Check the val predictions
val_dataloader = DataLoader(val_dataset, batch_size=4)
val_predictions = []
model.eval()
for batch in val_dataloader:
    with torch.no_grad():
        outputs = model(**batch)
    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)
    val_predictions.extend(predictions.cpu().numpy())

In [74]:
# Check the train predictions
train_dataloader = DataLoader(train_dataset, batch_size=4)
train_predictions = []
model.eval()
for batch in train_dataloader:
    with torch.no_grad():
        outputs = model(**batch)
    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)
    train_predictions.extend(predictions.cpu().numpy())

/tmp/ipykernel_14622/3879171852.py:9: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long).to(device)


In [75]:
# Check the val predictions
val_dataloader = DataLoader(val_dataset, batch_size=8)
val_predictions = []
model.eval()
for batch in val_dataloader:
    with torch.no_grad():
        outputs = model(**batch)
    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)
    val_predictions.extend(predictions.cpu().numpy())

In [76]:
# Check the confusion matrix of validation dataset
y_val = val_labels
# y_val = y_val.detach().cpu().numpy()
print(confusion_matrix(y_val, val_predictions))
print(classification_report(y_val, val_predictions))
print("Accuracy (validation):", accuracy_score(y_val, val_predictions))

[[ 460  205   76]
 [ 367 1375  412]
 [ 158  613 1096]]
              precision    recall  f1-score   support

           0       0.47      0.62      0.53       741
           1       0.63      0.64      0.63      2154
           2       0.69      0.59      0.64      1867

    accuracy                           0.62      4762
   macro avg       0.60      0.62      0.60      4762
weighted avg       0.63      0.62      0.62      4762

Accuracy (validation): 0.615497690046199


In [77]:
# Check the confusion matrix of train dataset
y_train = train_labels
# y_val = y_val.detach().cpu().numpy()
print(confusion_matrix(y_train, train_predictions))
print(classification_report(y_train, train_predictions))
print("Accuracy (training):", accuracy_score(y_train, train_predictions))

[[4359 1636  669]
 [1585 6194 1885]
 [ 817 2845 6002]]
              precision    recall  f1-score   support

         0.0       0.64      0.65      0.65      6664
         1.0       0.58      0.64      0.61      9664
         2.0       0.70      0.62      0.66      9664

    accuracy                           0.64     25992
   macro avg       0.64      0.64      0.64     25992
weighted avg       0.64      0.64      0.64     25992

Accuracy (training): 0.6369267466912897


## 3. Make predictions on your test dataset

In [19]:
# Implement this
print(test_df.shape)
test_df.isna().sum()
test_df["tweet"] = test_df["tweet"].fillna(value='')

(12032, 1)


In [20]:
test_texts = test_df["tweet"].tolist()
test_encodings = tokenizer(test_texts,
                          truncation=True,
                          padding=True)
test_dataset = ReviewDataset(test_encodings, [0]*len(test_texts))

In [21]:
test_dataloader = DataLoader(test_dataset, batch_size=4)
test_predictions = []
model.eval()
for batch in test_dataloader:
    with torch.no_grad():
        outputs = model(**batch)
    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)
    test_predictions.extend(predictions.cpu().numpy())

In [22]:
print(len(test_predictions))

12032


## 4. Write your predictions to a CSV file
You can use the following code to write your test predictions to a CSV file. Then upload your file to https://mlu.corp.amazon.com/contests/redirect/53

In [23]:
result_df = pd.DataFrame()
result_df["tweet"] = test_df["tweet"]
result_df["label"] = test_predictions
 
result_df.to_csv("../../data/open_data_sentiment_analysis/result.csv", encoding='utf-8', index=False)